### ISSUE TITLE
Leonteq Bitcoin Tracker

### ISSUE THREAD

**Issue by onedaysg1983** [nvk/bitcointreasuries.org#113]
- [ ] Name: Leonteq Bitcoin Tracker USD
- [ ] Exchange: SIX Swiss Exchange
- [ ] Link to google finance or wherever I can find it: https://www.six-structured-products.com/en/zertifikat/tracker-zertifikat-CH0481487988
- [ ] Basis price: $61'751'327 USD
- [ ] Market Cap: $61'751'327 USD
- [ ] Total BTC: 2'173.6 BTC
- [ ] Direct link to latest financial report: https://secure.six-securities-services.com/registration/HENFGOBOCEPJHIEFFMAEDOFJDJNILCBHKJDKKPABDBKLOEAPMPAIFAAHEMBDJAJIMNGMJBCHOLACKNCMFFFOCBHJJDEODHEMJR2UZEdjeuvx1wfoMIe5jXEwVL0hYONN7WfZMjUPMLlGGCHo8iiAQO97kWE9tHAAU6Ci
- [ ] Explantation: Quantity of 21'736 Certificates each 0.1 XBT outstanding as of 02.01.2021

**Please review existing <a href="https://github.com/nvk/bitcointreasuries.org/issues?q=is%3Aissue+is%3Aclosed">closed</a> and open issues before creating a new submission, don't submit just an article without any other information.**

**Comment by nvk** [comment]
IS this a ETF like product with AUM?

**Comment by onedaysg1983** [comment]
it is an exchange traded product tracking the price of a bitcoin (after 
fees).
------ Original Nachricht ------
Am  Donnerstag, 7. Jan, 2021 um 02:49, nvk schrieb:


IS this a ETF like product with AUM?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://github.com/nvk/bitcointreasuries.org/issues/113#issuecomment-755831051> 
, or unsubscribe

**Comment by nvk** [comment]
What's not clear is this BTC on their balance sheet or is this Asset Under Management like for example GBTC.

**Comment by onedaysg1983** [comment]
AuM
------ Original Nachricht ------
Am  Donnerstag, 7. Jan, 2021 um 22:26, nvk schrieb:


What's not clear is this BTC on their balance sheet or is this Asset 
Under Management like for example GBTC.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://github.com/nvk/bitcointreasuries.org/issues/113#issuecomment-756395199> 
, or unsubscribe

**Comment by nvk** [comment]
What is the password to put on the link so that people can freely see the financials link https://www.six-structured-products.com/en/zertifikat/tracker-zertifikat-CH0481487988

**Comment by onedaysg1983** [comment]
direct link seems not working. Work around:
a)
https://secure.six-securities-services.com/registration/WertrechteIsinReport
b)
ISIN: CH0481487988
—> check column „Quantity“ (e.g Quantity 1 is equivalent to 0.1 BTC as 
the product is 1/10 of a BTC)
------ Original Nachricht ------
Am  Donnerstag, 7. Jan, 2021 um 22:47, nvk schrieb:


What is the password to put on the link so that people can freely see 
the financials link 
https://www.six-structured-products.com/en/zertifikat/tracker-zertifikat-CH0481487988 
<https://www.six-structured-products.com/en/zertifikat/tracker-zertifikat-CH0481487988>
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub 
<https://github.com/nvk/bitcointreasuries.org/issues/113#issuecomment-756405695> 
, or unsubscribe

**Comment by nvk** [comment]
live https://twitter.com/BTCtreasuries/status/1347550838580015104?s=20
